In [22]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

temperature = temperature + 2

print("Temperature after adding error:")
print(temperature)

fahrenheit = (temperature * 9 / 5) + 32

print("Temperature in Fahrenheit:")
print(fahrenheit)

readings = temperature[temperature > 32]

print("Readings greater than 32:")
print(readings)

count = np.sum(temperature > 32)

print("Number of readings greater than 32:")
print(count)

# Vectorization allows NumPy to perform operations on all elements of an array
# at the same time without using a for loop. It makes the code shorter and
# more efficient. Boolean indexing allows us to select only the elements that
# satisfy a given condition, such as temperatures greater than 32 degrees.

Temperature after adding error:
[27 30 33 37 40 29 35 42]
Temperature in Fahrenheit:
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32:
[33 37 40 35 42]
Number of readings greater than 32:
5


In [23]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Total steps:", np.sum(steps))

print("Mean steps:", np.mean(steps))

print("Maximum steps:", np.max(steps))

print("Minimum steps:", np.min(steps))

print("Total steps for each day:")
print(np.sum(steps, axis=0))

print("Total steps for each user:")
print(np.sum(steps, axis=1))

max_position = np.unravel_index(np.argmax(steps), steps.shape)

print("Position of maximum steps:", max_position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day:
[26500 27300 30400]
Total steps for each user:
[18300 24500 14400 27000]
Position of maximum steps: (np.int64(3), np.int64(2))


In [24]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])

print(original)

[1 2 3 4 5 6]


In [25]:
subset = original[1:5]

print("Subset:")
print(subset)

Subset:
[2 3 4 5]


In [26]:
subset[0] = 999

print("Original:")
print(original)

print("Subset:")
print(subset)

Original:
[  1 999   3   4   5   6]
Subset:
[999   3   4   5]


In [27]:
copied_array = original[1:5].copy()

copied_array[0] = 500

print("Original:")
print(original)

print("Copied array:")
print(copied_array)

Original:
[  1 999   3   4   5   6]
Copied array:
[500   3   4   5]


In [28]:
arr = np.arange(1, 13)

matrix = arr.reshape(3, 4)

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
print("First row:")
print(matrix[0, :])

First row:
[1 2 3 4]


In [30]:
print("Last row:")
print(matrix[-1, :])

Last row:
[ 9 10 11 12]


In [31]:
print("Second column:")
print(matrix[:, 1])

Second column:
[ 2  6 10]


In [32]:
print("Rows 1-2 and columns 2-3:")
print(matrix[0:2, 1:3])

Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]


In [33]:
flat_array = matrix.flatten()

ravel_array = matrix.ravel()

print("Flatten:")
print(flat_array)

print("Ravel:")
print(ravel_array)

Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
ravel_array[0] = 100

print("Ravel array:")
print(ravel_array)

print("Original matrix:")
print(matrix)

Ravel array:
[100   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [35]:
flat_array[1] = 200

print("Flatten array:")
print(flat_array)

print("Original matrix:")
print(matrix)

Flatten array:
[  1 200   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [36]:
print("Shape:", matrix.shape)

print("Dimensions:", matrix.ndim)

print("Size:", matrix.size)

print("Data type:", matrix.dtype)

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [37]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)

print("Dimensions of X:", X.ndim)

Shape of X: (4, 3)
Dimensions of X: 2


In [38]:
X_T = X.T

print("Transpose of X:")
print(X_T)

Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]


In [39]:
result = X.T @ X

print("X.T @ X:")
print(result)

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [40]:
inverse = np.linalg.inv(X.T @ X)

print("Inverse:")
print(inverse)

Inverse:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


In [43]:
beta = np.linalg.inv(X.T @ X) @ X.T @ y

print("Coefficients:")
print(beta)

# The three coefficients represent the effect of the three features on the
# assistance score. The first coefficient represents sleep hours, the second
# represents activity level, and the third represents stress level. A positive
# coefficient means that increasing the feature increases the predicted score,
# while a negative coefficient means that increasing the feature decreases
# the predicted score.

Coefficients:
[-0.15921454  0.14083853 10.06302242]


In [44]:
new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("Predicted assistance score:", predicted_score)

Predicted assistance score: 75.27862544779018
