In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)

print("After adding 2:", arr + 2)

print("After multiplying by 3:", arr * 3)

print("After dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("Original array:", arr)

print("Reversed array:", arr[::-1])

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [3]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

index = np.argmax(counts)

most_frequent = values[index]

indices = np.where(x == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 5 7 8 9]


In [4]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

index = np.argmax(counts)

most_frequent = values[index]

indices = np.where(y == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 1 2]


In [5]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("1st row, 2nd column:", arr[0, 1])

print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [6]:
import numpy as np

Sujal = np.linspace(10, 100, 25)

print("Array:")
print(Sujal)

print("Dimensions:", Sujal.ndim)

print("Shape:", Sujal.shape)

print("Total elements:", Sujal.size)

print("Data type:", Sujal.dtype)

print("Total bytes:", Sujal.nbytes)

transpose_Sujal = Sujal.reshape(25, 1)

print("Transpose using reshape:")
print(transpose_Sujal)

print("Transpose using T:")
print(Sujal.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [7]:
import numpy as np

ucs420_Sujal = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original array:")
print(ucs420_Sujal)

print("Mean:", np.mean(ucs420_Sujal))

print("Median:", np.median(ucs420_Sujal))

print("Maximum:", np.max(ucs420_Sujal))

print("Minimum:", np.min(ucs420_Sujal))

print("Unique elements:", np.unique(ucs420_Sujal))

reshaped_ucs420_Sujal = ucs420_Sujal.reshape(4, 3)

print("Reshaped array:")
print(reshaped_ucs420_Sujal)

resized_ucs420_Sujal = np.resize(ucs420_Sujal, (2, 3))

print("Resized array:")
print(resized_ucs420_Sujal)

Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
